name: NaurelliaModeration
version: '${project.version}'
main: fr.armotik.naurelliamoderation.NaurelliaModeration
api-version: 1.19
authors: [ Armotik ]
description: Moderation plugin for NaurelliaCraft
website: naurellia.com
